import { FuturesMarketKey } from '../types/futures';

export const PROTOCOLS =
	'OPTIMISM_UNISWAP_V3,OPTIMISM_SYNTHETIX,OPTIMISM_SYNTHETIX_WRAPPER,OPTIMISM_ONE_INCH_LIMIT_ORDER,OPTIMISM_ONE_INCH_LIMIT_ORDER_V2,OPTIMISM_CURVE,OPTIMISM_BALANCER_V2,OPTIMISM_VELODROME,OPTIMISM_KYBERSWAP_ELASTIC';

export const FILTERED_TOKENS = ['0x4922a015c4407f87432b179bb209e125432e4a2a'];
export const DEFAULT_BUFFER = 0.2;

export const ADDITIONAL_MARKETS = new Set<string>([
	FuturesMarketKey.sAPEPERP,
	FuturesMarketKey.sDYDXPERP,
	FuturesMarketKey.sXAUPERP,
	FuturesMarketKey.sXAGPERP,
]);
